#!/bin/bash

set -euo pipefail

# Initialization - load function handler
# source ./"$(echo $_HANDLER | cut -d. -f1).sh"

# Info custom runtime ready
curl -d " " -X POST -s "http://$SCF_RUNTIME_API:$SCF_RUNTIME_API_PORT/runtime/init/ready"

# Processing
while true
do
  HEADERS="$(mktemp)"
  # Get an event. The HTTP request will block until one is received
  EVENT_DATA=$(curl -sS -LD "$HEADERS" -X GET -s "http://$SCF_RUNTIME_API:$SCF_RUNTIME_API_PORT/runtime/invocation/next")

  # Execute the handler function from the script
  # RESPONSE=$($(echo "$_HANDLER" | cut -d. -f2) <<< "$EVENT_DATA")
  # RESPONSE=$(TESSDATA_PREFIX=/opt LD_LIBRARY_PATH=/opt /opt/ssvm --dir /tmp/:/tmp/ "$_HANDLER" <<< "$EVENT_DATA")
  RESPONSE=$(/opt/ssvm --dir /tmp/:/tmp/ "$_HANDLER" <<< "$EVENT_DATA")
  # RESPONSE=$(ldd /opt/tesseract)
  # RESPONSE=$(/opt/tesseract test-chinese.png stdout --dpi 70 -l chi_sim)

  # Send the response
  curl -X POST -s "http://$SCF_RUNTIME_API:$SCF_RUNTIME_API_PORT/runtime/invocation/response"  -d "$RESPONSE"
done
